// Generated by tools/render-lineup.mjs — do not edit by hand.
//
// How many micrometres wide each lineup picture is. For most specimens that
// equals the declared size, but a neuron with its processes and a sperm with
// its flagellum are wider than the structure they are measured by, and the
// page has to draw them at that real width or the row would lie.
export const LINEUP_MICRONS = {
  "animal-cell": 20,
  "plant-cell": 50,
  "cyanobacterium": 3,
  "white-blood-cell": 12,
  "neuron": 81.91,
  "red-blood-cell": 7.5,
  "sperm-cell": 24.84
};
