// Render the same-scale lineup: one image per specimen, all at one ortho scale.
//
//   npm run lineup
//
// Reads the declared sizes straight out of specimens.js so the renders and the
// page cannot disagree about how big anything is. Needs the .blend files, which
// the build scripts produce — run those first, as with npm run check:models.

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { specimens } from '../specimens.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const outDir = path.join(root, 'public', 'lineup');
const DEFAULT_BLENDER = 'D:\\code\\_tools\\blender-5.2.1-windows-x64\\blender.exe';
const blender = process.env.BLENDER ?? DEFAULT_BLENDER;

if (!existsSync(blender)) {
  console.error(`Blender not found at ${blender}. Set BLENDER to the executable.`);
  process.exit(2);
}

await mkdir(outDir, { recursive: true });

// How many micrometres wide each picture is, as measured while rendering. The
// page cannot derive this: the whole specimen is wider than the structure it is
// measured by, by a factor that only the model knows.
const manifest = {};
let rendered = 0;
for (const [id, cell] of Object.entries(specimens)) {
  if (!cell.size) continue;
  const blend = path.join(root, `${id}.blend`);
  if (!existsSync(blend)) {
    console.log(`  skip ${id}: no ${id}.blend (build it first)`);
    continue;
  }
  const result = spawnSync(blender, [
    '--background', '--factory-startup',
    '--python', path.join(here, 'render_lineup.py'),
    '--', `${id}.blend`, cell.size.structure, String(cell.size.real),
    path.join('public', 'lineup', `${id}.png`),
  ], { stdio: 'inherit', cwd: root });
  if (result.status !== 0) {
    console.error(`  ${id}: render failed`);
    process.exit(1);
  }
  const sidecar = JSON.parse(await readFile(path.join(outDir, `${id}.json`), 'utf8'));
  manifest[id] = sidecar.microns;
  rendered += 1;
}

await writeFile(path.join(outDir, 'scale.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

// Also as a module, because it is build-time data: the page can then size every
// picture at parse time instead of fetching a manifest and reflowing the row
// after the images have already appeared.
await writeFile(
  path.join(root, 'lineup-scale.js'),
  '// Generated by tools/render-lineup.mjs — do not edit by hand.\n'
  + '//\n'
  + '// How many micrometres wide each lineup picture is. For most specimens that\n'
  + '// equals the declared size, but a neuron with its processes and a sperm with\n'
  + '// its flagellum are wider than the structure they are measured by, and the\n'
  + '// page has to draw them at that real width or the row would lie.\n'
  + `export const LINEUP_MICRONS = ${JSON.stringify(manifest, null, 2)};\n`,
  'utf8',
);

console.log(`\n  ${rendered} lineup image(s) in public/lineup/`);
console.log(`  widths: ${Object.entries(manifest).map(([id, µm]) => `${id} ${µm}µm`).join(', ')}`);

